In [38]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [39]:
df = pd.read_csv('Datasets/train_final.csv')

In [40]:
df

,MAGIC_KEY,PURCHASE_COUNT,TOTAL_AMOUNT_SPENT,LAST_PURCHASE_DATE,DAY_SINCE_LAST_PURCHASE,AVERAGE_DIFF,10_2018_FIRST_15,11_2018_FIRST_15,12_2018_FIRST_15,1_2019_FIRST_15,...,MILK_12_2018_FIRST_15,MEAT_12_2018_FIRST_15,MILK_1_2019_FIRST_15,MEAT_1_2019_FIRST_15,MEAT_2_2019_FIRST_15,T_PURCHASE_10_2018_FIRST_15,T_PURCHASE_11_2018_FIRST_15,T_PURCHASE_12_2018_FIRST_15,T_PURCHASE_1_2019_FIRST_15,T_PURCHASE_2_2019_FIRST_15
0,249670911D8,2,24.10,2019-02-02,27 days,93 days 00:00:00,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
1,249751FC4DD,1,17.98,2018-10-12,140 days,0 days 00:00:00,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
2,24978027606,1,15.96,2018-10-19,133 days,0 days 00:00:00,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,24979164422,1,13.96,2018-11-30,91 days,0 days 00:00:00,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,2497B8B4FDA,2,33.94,2018-11-01,120 days,29 days 00:00:00,1.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1274096,2E6F72C6F1C,3,51.94,2019-02-27,2 days,64 days 12:00:00,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.5,0.0,0.0,0.0,0.0,1.0
1274097,2E6F8194908,1,11.96,2019-02-23,6 days,0 days 00:00:00,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1274098,2E6F9C7B9B4,1,19.98,2019-01-28,32 days,0 days 00:00:00,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1274099,2E6FB0EBB32,6,107.88,2019-02-11,18 days,26 days 14:24:00,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,2.2,1.0,0.0,0.0,0.0,1.0
1274100,2E6FBE224FA,1,11.96,2019-02-20,9 days,0 days 00:00:00,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [41]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1274101 entries, 0 to 1274100
Data columns (total 31 columns):
 #   Column                       Non-Null Count    Dtype
---  ------                       --------------    -----
 0   MAGIC_KEY                    1274101 non-null  object
 1   PURCHASE_COUNT               1274101 non-null  int64
 2   TOTAL_AMOUNT_SPENT           1274101 non-null  float64
 3   LAST_PURCHASE_DATE           1274101 non-null  object
 4   DAY_SINCE_LAST_PURCHASE      1274101 non-null  object
 5   AVERAGE_DIFF                 1274101 non-null  object
 6   10_2018_FIRST_15             1274101 non-null  float64
 7   11_2018_FIRST_15             1274101 non-null  float64
 8   12_2018_FIRST_15             1274101 non-null  float64
 9   1_2019_FIRST_15              1274101 non-null  float64
 10  2_2019_FIRST_15              1274101 non-null  float64
 11  LAST_MILK_PURCHASE           1274101 non-null  float64
 12  LAST_MEAT_PURCHASE           1274101 non-null  float64
 13  MODE_BOX_ID                  1274101 non-null  float64
 14  MODE_BOX_ID_MILK             1274101 non-null  float64
 15  MODE_BOX_ID_MEAT             1274101 non-null  float64
 16  MODE_BOX_ID_UNIT_PRICE       1274101 non-null  float64
 17  MILK_10_2018_FIRST_15        1274101 non-null  float64
 18  MEAT_10_2018_FIRST_15        1274101 non-null  float64
 19  MILK_11_2018_FIRST_15        1274101 non-null  float64
 20  MEAT_11_2018_FIRST_15        1274101 non-null  float64
 21  MILK_12_2018_FIRST_15        1274101 non-null  float64
 22  MEAT_12_2018_FIRST_15        1274101 non-null  float64
 23  MILK_1_2019_FIRST_15         1274101 non-null  float64
 24  MEAT_1_2019_FIRST_15         1274101 non-null  float64
 25  MEAT_2_2019_FIRST_15         1274101 non-null  float64
 26  T_PURCHASE_10_2018_FIRST_15  1274101 non-null  float64
 27  T_PURCHASE_11_2018_FIRST_15  1274101 non-null  float64
 28  T_PURCHASE_12_2018_FIRST_15  1274101 non-null  float64
 29  T_PURCHASE_1_2019_FIRST_15   1274101 non-null  float64
 30  T_PURCHASE_2_2019_FIRST_15   1274101 non-null  float64
dtypes: float64(26), int64(1), object(4)
memory usage: 301.3+ MB

In [42]:
df['LAST_PURCHASE_DATE'] = pd.to_datetime(df['LAST_PURCHASE_DATE'])
df['DAY_SINCE_LAST_PURCHASE'] = pd.to_timedelta(df['DAY_SINCE_LAST_PURCHASE'])
df['AVERAGE_DIFF'] = pd.to_timedelta(df['AVERAGE_DIFF'])

In [43]:
df['DAY_SINCE_LAST_PURCHASE'] = df['DAY_SINCE_LAST_PURCHASE'].dt.days.astype(int)
df['AVERAGE_DIFF'] = df['AVERAGE_DIFF'].dt.days.astype(int)

In [44]:
df.drop(columns=['LAST_PURCHASE_DATE'], inplace=True)

In [45]:
df.head()

,MAGIC_KEY,PURCHASE_COUNT,TOTAL_AMOUNT_SPENT,DAY_SINCE_LAST_PURCHASE,AVERAGE_DIFF,10_2018_FIRST_15,11_2018_FIRST_15,12_2018_FIRST_15,1_2019_FIRST_15,2_2019_FIRST_15,...,MILK_12_2018_FIRST_15,MEAT_12_2018_FIRST_15,MILK_1_2019_FIRST_15,MEAT_1_2019_FIRST_15,MEAT_2_2019_FIRST_15,T_PURCHASE_10_2018_FIRST_15,T_PURCHASE_11_2018_FIRST_15,T_PURCHASE_12_2018_FIRST_15,T_PURCHASE_1_2019_FIRST_15,T_PURCHASE_2_2019_FIRST_15
0,249670911D8,2,24.10,27,93,0.0,1.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
1,249751FC4DD,1,17.98,140,0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
2,24978027606,1,15.96,133,0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,24979164422,1,13.96,91,0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,2497B8B4FDA,2,33.94,120,29,1.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0

In [46]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1274101 entries, 0 to 1274100
Data columns (total 30 columns):
 #   Column                       Non-Null Count    Dtype
---  ------                       --------------    -----
 0   MAGIC_KEY                    1274101 non-null  object
 1   PURCHASE_COUNT               1274101 non-null  int64
 2   TOTAL_AMOUNT_SPENT           1274101 non-null  float64
 3   DAY_SINCE_LAST_PURCHASE      1274101 non-null  int32
 4   AVERAGE_DIFF                 1274101 non-null  int32
 5   10_2018_FIRST_15             1274101 non-null  float64
 6   11_2018_FIRST_15             1274101 non-null  float64
 7   12_2018_FIRST_15             1274101 non-null  float64
 8   1_2019_FIRST_15              1274101 non-null  float64
 9   2_2019_FIRST_15              1274101 non-null  float64
 10  LAST_MILK_PURCHASE           1274101 non-null  float64
 11  LAST_MEAT_PURCHASE           1274101 non-null  float64
 12  MODE_BOX_ID                  1274101 non-null  float64
 13  MODE_BOX_ID_MILK             1274101 non-null  float64
 14  MODE_BOX_ID_MEAT             1274101 non-null  float64
 15  MODE_BOX_ID_UNIT_PRICE       1274101 non-null  float64
 16  MILK_10_2018_FIRST_15        1274101 non-null  float64
 17  MEAT_10_2018_FIRST_15        1274101 non-null  float64
 18  MILK_11_2018_FIRST_15        1274101 non-null  float64
 19  MEAT_11_2018_FIRST_15        1274101 non-null  float64
 20  MILK_12_2018_FIRST_15        1274101 non-null  float64
 21  MEAT_12_2018_FIRST_15        1274101 non-null  float64
 22  MILK_1_2019_FIRST_15         1274101 non-null  float64
 23  MEAT_1_2019_FIRST_15         1274101 non-null  float64
 24  MEAT_2_2019_FIRST_15         1274101 non-null  float64
 25  T_PURCHASE_10_2018_FIRST_15  1274101 non-null  float64
 26  T_PURCHASE_11_2018_FIRST_15  1274101 non-null  float64
 27  T_PURCHASE_12_2018_FIRST_15  1274101 non-null  float64
 28  T_PURCHASE_1_2019_FIRST_15   1274101 non-null  float64
 29  T_PURCHASE_2_2019_FIRST_15   1274101 non-null  float64
dtypes: float64(26), int32(2), int64(1), object(1)
memory usage: 281.9+ MB

In [47]:
from sklearn.preprocessing import LabelEncoder #importing the labenconder
le = LabelEncoder() #creating an instance of LabelEncoder

df['MAGIC_KEY_ENCODED'] = le.fit_transform(df['MAGIC_KEY'])
df_encoded = df.drop(columns = ['MAGIC_KEY'])

In [48]:
df_encoded.head()

,PURCHASE_COUNT,TOTAL_AMOUNT_SPENT,DAY_SINCE_LAST_PURCHASE,AVERAGE_DIFF,10_2018_FIRST_15,11_2018_FIRST_15,12_2018_FIRST_15,1_2019_FIRST_15,2_2019_FIRST_15,LAST_MILK_PURCHASE,...,MEAT_12_2018_FIRST_15,MILK_1_2019_FIRST_15,MEAT_1_2019_FIRST_15,MEAT_2_2019_FIRST_15,T_PURCHASE_10_2018_FIRST_15,T_PURCHASE_11_2018_FIRST_15,T_PURCHASE_12_2018_FIRST_15,T_PURCHASE_1_2019_FIRST_15,T_PURCHASE_2_2019_FIRST_15,MAGIC_KEY_ENCODED
0,2,24.10,27,93,0.0,1.0,0.0,0.0,1.0,8.5,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0
1,1,17.98,140,0,1.0,0.0,0.0,0.0,0.0,10.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1
2,1,15.96,133,0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2
3,1,13.96,91,0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3
4,2,33.94,120,29,1.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,4

In [49]:
correlation = df_encoded.corr(method = 'pearson') #finding all correlation between each features
print(correlation['MEAT_2_2019_FIRST_15'].sort_values(ascending = False).to_string()) #printing correlation with class in descending order

MEAT_2_2019_FIRST_15           1.000000
2_2019_FIRST_15                0.888807
T_PURCHASE_2_2019_FIRST_15     0.880875
MEAT_1_2019_FIRST_15           0.235694
LAST_MEAT_PURCHASE             0.226680
TOTAL_AMOUNT_SPENT             0.216939
PURCHASE_COUNT                 0.215804
MODE_BOX_ID_MEAT               0.192700
1_2019_FIRST_15                0.184610
T_PURCHASE_1_2019_FIRST_15     0.182462
AVERAGE_DIFF                   0.143966
MILK_1_2019_FIRST_15           0.135864
MEAT_12_2018_FIRST_15          0.100410
12_2018_FIRST_15               0.065422
T_PURCHASE_12_2018_FIRST_15    0.064572
MILK_12_2018_FIRST_15          0.051609
MEAT_11_2018_FIRST_15          0.037913
MODE_BOX_ID                    0.026633
MODE_BOX_ID_UNIT_PRICE         0.024402
MILK_11_2018_FIRST_15          0.012789
11_2018_FIRST_15               0.007049
T_PURCHASE_11_2018_FIRST_15    0.006656
MAGIC_KEY_ENCODED             -0.000352
MEAT_10_2018_FIRST_15         -0.001826
MILK_10_2018_FIRST_15         -0.015683
T_PURCHASE_10_2018_FIRST_15   -0.025735
10_2018_FIRST_15              -0.026230
LAST_MILK_PURCHASE            -0.075910
MODE_BOX_ID_MILK              -0.085971
DAY_SINCE_LAST_PURCHASE       -0.357223

In [50]:
from sklearn.utils import shuffle #importing the suffle module
shuffled_df = shuffle(df_encoded)
shuffled_df #checking

,PURCHASE_COUNT,TOTAL_AMOUNT_SPENT,DAY_SINCE_LAST_PURCHASE,AVERAGE_DIFF,10_2018_FIRST_15,11_2018_FIRST_15,12_2018_FIRST_15,1_2019_FIRST_15,2_2019_FIRST_15,LAST_MILK_PURCHASE,...,MEAT_12_2018_FIRST_15,MILK_1_2019_FIRST_15,MEAT_1_2019_FIRST_15,MEAT_2_2019_FIRST_15,T_PURCHASE_10_2018_FIRST_15,T_PURCHASE_11_2018_FIRST_15,T_PURCHASE_12_2018_FIRST_15,T_PURCHASE_1_2019_FIRST_15,T_PURCHASE_2_2019_FIRST_15,MAGIC_KEY_ENCODED
347089,2,39.96,96,49,1.0,0.0,0.0,0.0,0.0,16.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,347089
127111,1,17.98,35,0,0.0,0.0,0.0,0.0,0.0,8.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,127111
758065,1,15.98,36,0,0.0,0.0,0.0,0.0,0.0,8.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,758065
721073,1,19.98,114,0,0.0,1.0,0.0,0.0,0.0,12.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,721073
511770,2,39.96,33,33,0.0,0.0,0.0,0.0,0.0,16.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,511770
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1047584,6,113.88,12,15,0.0,0.0,1.0,1.0,1.0,10.0,...,2.5,20.0,4.0,1.8,0.0,0.0,2.0,2.0,1.0,1047584
121969,5,89.90,28,25,0.0,0.0,1.0,1.0,1.0,8.0,...,2.2,8.0,2.2,2.2,0.0,0.0,1.0,1.0,1.0,121969
694026,1,23.98,79,0,0.0,0.0,1.0,0.0,0.0,11.0,...,2.2,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,694026
321672,4,55.84,39,26,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,321672
196164,1,17.98,42,0,0.0,0.0,0.0,0.0,0.0,8.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,196164

In [51]:
#rearranging the index value
rearranged_df = shuffled_df.reset_index(drop = True)
rearranged_df

,PURCHASE_COUNT,TOTAL_AMOUNT_SPENT,DAY_SINCE_LAST_PURCHASE,AVERAGE_DIFF,10_2018_FIRST_15,11_2018_FIRST_15,12_2018_FIRST_15,1_2019_FIRST_15,2_2019_FIRST_15,LAST_MILK_PURCHASE,...,MEAT_12_2018_FIRST_15,MILK_1_2019_FIRST_15,MEAT_1_2019_FIRST_15,MEAT_2_2019_FIRST_15,T_PURCHASE_10_2018_FIRST_15,T_PURCHASE_11_2018_FIRST_15,T_PURCHASE_12_2018_FIRST_15,T_PURCHASE_1_2019_FIRST_15,T_PURCHASE_2_2019_FIRST_15,MAGIC_KEY_ENCODED
0,2,39.96,96,49,1.0,0.0,0.0,0.0,0.0,16.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,347089
1,1,17.98,35,0,0.0,0.0,0.0,0.0,0.0,8.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,127111
2,1,15.98,36,0,0.0,0.0,0.0,0.0,0.0,8.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,758065
3,1,19.98,114,0,0.0,1.0,0.0,0.0,0.0,12.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,721073
4,2,39.96,33,33,0.0,0.0,0.0,0.0,0.0,16.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,511770
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1274096,6,113.88,12,15,0.0,0.0,1.0,1.0,1.0,10.0,...,2.5,20.0,4.0,1.8,0.0,0.0,2.0,2.0,1.0,1047584
1274097,5,89.90,28,25,0.0,0.0,1.0,1.0,1.0,8.0,...,2.2,8.0,2.2,2.2,0.0,0.0,1.0,1.0,1.0,121969
1274098,1,23.98,79,0,0.0,0.0,1.0,0.0,0.0,11.0,...,2.2,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,694026
1274099,4,55.84,39,26,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,321672
1274100,1,17.98,42,0,0.0,0.0,0.0,0.0,0.0,8.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,196164

In [52]:
X = rearranged_df.drop(columns = ['MEAT_2_2019_FIRST_15']) #dropping the class collumn to separate the feature
X

,PURCHASE_COUNT,TOTAL_AMOUNT_SPENT,DAY_SINCE_LAST_PURCHASE,AVERAGE_DIFF,10_2018_FIRST_15,11_2018_FIRST_15,12_2018_FIRST_15,1_2019_FIRST_15,2_2019_FIRST_15,LAST_MILK_PURCHASE,...,MILK_12_2018_FIRST_15,MEAT_12_2018_FIRST_15,MILK_1_2019_FIRST_15,MEAT_1_2019_FIRST_15,T_PURCHASE_10_2018_FIRST_15,T_PURCHASE_11_2018_FIRST_15,T_PURCHASE_12_2018_FIRST_15,T_PURCHASE_1_2019_FIRST_15,T_PURCHASE_2_2019_FIRST_15,MAGIC_KEY_ENCODED
0,2,39.96,96,49,1.0,0.0,0.0,0.0,0.0,16.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,347089
1,1,17.98,35,0,0.0,0.0,0.0,0.0,0.0,8.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,127111
2,1,15.98,36,0,0.0,0.0,0.0,0.0,0.0,8.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,758065
3,1,19.98,114,0,0.0,1.0,0.0,0.0,0.0,12.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,721073
4,2,39.96,33,33,0.0,0.0,0.0,0.0,0.0,16.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,511770
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1274096,6,113.88,12,15,0.0,0.0,1.0,1.0,1.0,10.0,...,21.0,2.5,20.0,4.0,0.0,0.0,2.0,2.0,1.0,1047584
1274097,5,89.90,28,25,0.0,0.0,1.0,1.0,1.0,8.0,...,8.0,2.2,8.0,2.2,0.0,0.0,1.0,1.0,1.0,121969
1274098,1,23.98,79,0,0.0,0.0,1.0,0.0,0.0,11.0,...,11.0,2.2,0.0,0.0,0.0,0.0,1.0,0.0,0.0,694026
1274099,4,55.84,39,26,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,321672
1274100,1,17.98,42,0,0.0,0.0,0.0,0.0,0.0,8.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,196164

In [53]:
y =  rearranged_df['MEAT_2_2019_FIRST_15'] #separating target to y
y

0          0.0
1          0.0
2          0.0
3          0.0
4          0.0
          ...
1274096    1.8
1274097    2.2
1274098    0.0
1274099    0.0
1274100    0.0
Name: MEAT_2_2019_FIRST_15, Length: 1274101, dtype: float64

In [54]:
from sklearn.model_selection import train_test_split #importing module
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20) #80-20% split

In [55]:
print(len(X_train)) #checking
print(len(X_test))

1019280
254821

In [56]:
print(len(y_train)) #checking
print(len(y_test))

1019280
254821

#using MinMax Scaler
from sklearn.preprocessing import MinMaxScaler #importing scaler

scaler = MinMaxScaler() #creating an instance

#we can scale the features only, not the target
X_train = scaler.fit_transform(X_train)
X_test = scaler.fit_transform(X_test)

In [57]:
#importing the model first
from sklearn.linear_model import LinearRegression
reg = LinearRegression() #creating an instance of the model using default parameter
reg.fit(X_train, y_train)

LinearRegression()

In [58]:
y_pred = reg.predict(X_test)

In [59]:
from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error
import math

In [60]:
R2 = r2_score(y_pred, y_test) #checking R2 Score
print("R2: ", R2)

MSE = mean_squared_error(y_pred, y_test) #checking Mean Squared Error
print("MSE: ", MSE)

RMSE = math.sqrt(MSE) #checking Root Mean Squared Error
print("RMSE: ", RMSE)

MAE = mean_absolute_error(y_pred, y_test) #cehcking Mean Absolute Error
print("MAE: ", MAE)

R2:  0.8125410942795491
MSE:  0.16335464675141959
RMSE:  0.40417155608901967
MAE:  0.23445158368177546

In [61]:
from sklearn.ensemble import RandomForestRegressor
rand_forest = RandomForestRegressor(n_estimators=25, max_depth=26, n_jobs=-1, random_state=42)
rand_forest.fit(X_train, y_train)

RandomForestRegressor(max_depth=26, n_estimators=25, n_jobs=-1, random_state=42)

In [62]:
y_pred = rand_forest.predict(X_test)

In [63]:
R2 = r2_score(y_pred, y_test) #checking R2 Score
print("R2: ", R2)

MSE = mean_squared_error(y_pred, y_test) #checking Mean Squared Error
print("MSE: ", MSE)

RMSE = math.sqrt(MSE) #checking Root Mean Squared Error
print("RMSE: ", RMSE)

MAE = mean_absolute_error(y_pred, y_test) #cehcking Mean Absolute Error
print("MAE: ", MAE)

R2:  0.993810318087682
MSE:  0.00637781355967528
RMSE:  0.07986121436389056
MAE:  0.005172351389715136

In [64]:
df_problem = pd.read_csv('Datasets/problem 3.csv')
df_problem

        MAGIC_KEY
0     2BCFE9C06A7
1     2C2A872B5A2
2     2C6A897671B
3     2C6F1287F53
4     2C658198CC9
...           ...
5374  2C0804EFE49
5375  2C080B48630
5376  2C08243C58E
5377  2C082C78575
5378  2C083B1F3E5

[5379 rows x 1 columns]

In [65]:
df

,MAGIC_KEY,PURCHASE_COUNT,TOTAL_AMOUNT_SPENT,DAY_SINCE_LAST_PURCHASE,AVERAGE_DIFF,10_2018_FIRST_15,11_2018_FIRST_15,12_2018_FIRST_15,1_2019_FIRST_15,2_2019_FIRST_15,...,MEAT_12_2018_FIRST_15,MILK_1_2019_FIRST_15,MEAT_1_2019_FIRST_15,MEAT_2_2019_FIRST_15,T_PURCHASE_10_2018_FIRST_15,T_PURCHASE_11_2018_FIRST_15,T_PURCHASE_12_2018_FIRST_15,T_PURCHASE_1_2019_FIRST_15,T_PURCHASE_2_2019_FIRST_15,MAGIC_KEY_ENCODED
0,249670911D8,2,24.10,27,93,0.0,1.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0
1,249751FC4DD,1,17.98,140,0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1
2,24978027606,1,15.96,133,0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2
3,24979164422,1,13.96,91,0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3
4,2497B8B4FDA,2,33.94,120,29,1.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1274096,2E6F72C6F1C,3,51.94,2,64,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,1.5,0.0,0.0,0.0,0.0,1.0,1274096
1274097,2E6F8194908,1,11.96,6,0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1274097
1274098,2E6F9C7B9B4,1,19.98,32,0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1274098
1274099,2E6FB0EBB32,6,107.88,18,26,1.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,2.2,1.0,0.0,0.0,0.0,1.0,1274099
1274100,2E6FBE224FA,1,11.96,9,0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1274100

In [66]:
df

,MAGIC_KEY,PURCHASE_COUNT,TOTAL_AMOUNT_SPENT,DAY_SINCE_LAST_PURCHASE,AVERAGE_DIFF,10_2018_FIRST_15,11_2018_FIRST_15,12_2018_FIRST_15,1_2019_FIRST_15,2_2019_FIRST_15,...,MEAT_12_2018_FIRST_15,MILK_1_2019_FIRST_15,MEAT_1_2019_FIRST_15,MEAT_2_2019_FIRST_15,T_PURCHASE_10_2018_FIRST_15,T_PURCHASE_11_2018_FIRST_15,T_PURCHASE_12_2018_FIRST_15,T_PURCHASE_1_2019_FIRST_15,T_PURCHASE_2_2019_FIRST_15,MAGIC_KEY_ENCODED
0,249670911D8,2,24.10,27,93,0.0,1.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0
1,249751FC4DD,1,17.98,140,0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1
2,24978027606,1,15.96,133,0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2
3,24979164422,1,13.96,91,0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3
4,2497B8B4FDA,2,33.94,120,29,1.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1274096,2E6F72C6F1C,3,51.94,2,64,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,1.5,0.0,0.0,0.0,0.0,1.0,1274096
1274097,2E6F8194908,1,11.96,6,0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1274097
1274098,2E6F9C7B9B4,1,19.98,32,0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1274098
1274099,2E6FB0EBB32,6,107.88,18,26,1.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,2.2,1.0,0.0,0.0,0.0,1.0,1274099
1274100,2E6FBE224FA,1,11.96,9,0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1274100

In [67]:
df_test = pd.merge(df_problem, df, on = 'MAGIC_KEY')
df_test

,MAGIC_KEY,PURCHASE_COUNT,TOTAL_AMOUNT_SPENT,DAY_SINCE_LAST_PURCHASE,AVERAGE_DIFF,10_2018_FIRST_15,11_2018_FIRST_15,12_2018_FIRST_15,1_2019_FIRST_15,2_2019_FIRST_15,...,MEAT_12_2018_FIRST_15,MILK_1_2019_FIRST_15,MEAT_1_2019_FIRST_15,MEAT_2_2019_FIRST_15,T_PURCHASE_10_2018_FIRST_15,T_PURCHASE_11_2018_FIRST_15,T_PURCHASE_12_2018_FIRST_15,T_PURCHASE_1_2019_FIRST_15,T_PURCHASE_2_2019_FIRST_15,MAGIC_KEY_ENCODED
0,2BCFE9C06A7,5,240.00,1,1,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,387282
1,2C2A872B5A2,2,43.96,87,64,1.0,0.0,1.0,0.0,0.0,...,2.2,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,683858
2,2C6A897671B,3,71.94,1,35,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,830258
3,2C6F1287F53,10,431.94,1,13,0.0,0.0,1.0,0.0,1.0,...,2.2,0.0,0.0,2.2,0.0,0.0,1.0,0.0,1.0,841123
4,2C658198CC9,3,71.94,25,26,0.0,0.0,1.0,1.0,1.0,...,2.2,10.0,2.2,2.2,0.0,0.0,1.0,1.0,1.0,818324
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5374,2C0804EFE49,1,11.96,76,0,0.0,0.0,1.0,0.0,0.0,...,2.5,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,583509
5375,2C080B48630,1,12.18,96,0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,583586
5376,2C08243C58E,1,11.96,29,0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,583875
5377,2C082C78575,1,12.98,127,0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,583977
5378,2C083B1F3E5,2,27.92,19,110,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,2.4,0.0,0.0,0.0,0.0,1.0,584154

In [68]:
df_test = df_test.drop(columns = ['MEAT_2_2019_FIRST_15'])
df_test

,MAGIC_KEY,PURCHASE_COUNT,TOTAL_AMOUNT_SPENT,DAY_SINCE_LAST_PURCHASE,AVERAGE_DIFF,10_2018_FIRST_15,11_2018_FIRST_15,12_2018_FIRST_15,1_2019_FIRST_15,2_2019_FIRST_15,...,MILK_12_2018_FIRST_15,MEAT_12_2018_FIRST_15,MILK_1_2019_FIRST_15,MEAT_1_2019_FIRST_15,T_PURCHASE_10_2018_FIRST_15,T_PURCHASE_11_2018_FIRST_15,T_PURCHASE_12_2018_FIRST_15,T_PURCHASE_1_2019_FIRST_15,T_PURCHASE_2_2019_FIRST_15,MAGIC_KEY_ENCODED
0,2BCFE9C06A7,5,240.00,1,1,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,387282
1,2C2A872B5A2,2,43.96,87,64,1.0,0.0,1.0,0.0,0.0,...,11.0,2.2,0.0,0.0,1.0,0.0,1.0,0.0,0.0,683858
2,2C6A897671B,3,71.94,1,35,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,830258
3,2C6F1287F53,10,431.94,1,13,0.0,0.0,1.0,0.0,1.0,...,11.0,2.2,0.0,0.0,0.0,0.0,1.0,0.0,1.0,841123
4,2C658198CC9,3,71.94,25,26,0.0,0.0,1.0,1.0,1.0,...,11.0,2.2,10.0,2.2,0.0,0.0,1.0,1.0,1.0,818324
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5374,2C0804EFE49,1,11.96,76,0,0.0,0.0,1.0,0.0,0.0,...,0.0,2.5,0.0,0.0,0.0,0.0,1.0,0.0,0.0,583509
5375,2C080B48630,1,12.18,96,0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,583586
5376,2C08243C58E,1,11.96,29,0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,583875
5377,2C082C78575,1,12.98,127,0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,583977
5378,2C083B1F3E5,2,27.92,19,110,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,584154

In [69]:
df_test_X = df_test.drop(columns = ['MAGIC_KEY'])
df_test_X

,PURCHASE_COUNT,TOTAL_AMOUNT_SPENT,DAY_SINCE_LAST_PURCHASE,AVERAGE_DIFF,10_2018_FIRST_15,11_2018_FIRST_15,12_2018_FIRST_15,1_2019_FIRST_15,2_2019_FIRST_15,LAST_MILK_PURCHASE,...,MILK_12_2018_FIRST_15,MEAT_12_2018_FIRST_15,MILK_1_2019_FIRST_15,MEAT_1_2019_FIRST_15,T_PURCHASE_10_2018_FIRST_15,T_PURCHASE_11_2018_FIRST_15,T_PURCHASE_12_2018_FIRST_15,T_PURCHASE_1_2019_FIRST_15,T_PURCHASE_2_2019_FIRST_15,MAGIC_KEY_ENCODED
0,5,240.00,1,1,0.0,0.0,0.0,0.0,0.0,10.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,387282
1,2,43.96,87,64,1.0,0.0,1.0,0.0,0.0,11.0,...,11.0,2.2,0.0,0.0,1.0,0.0,1.0,0.0,0.0,683858
2,3,71.94,1,35,0.0,0.0,0.0,0.0,0.0,10.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,830258
3,10,431.94,1,13,0.0,0.0,1.0,0.0,1.0,10.0,...,11.0,2.2,0.0,0.0,0.0,0.0,1.0,0.0,1.0,841123
4,3,71.94,25,26,0.0,0.0,1.0,1.0,1.0,10.0,...,11.0,2.2,10.0,2.2,0.0,0.0,1.0,1.0,1.0,818324
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5374,1,11.96,76,0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,2.5,0.0,0.0,0.0,0.0,1.0,0.0,0.0,583509
5375,1,12.18,96,0,0.0,0.0,0.0,0.0,0.0,10.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,583586
5376,1,11.96,29,0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,583875
5377,1,12.98,127,0,0.0,0.0,0.0,0.0,0.0,10.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,583977
5378,2,27.92,19,110,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,584154

#we can scale the features only, not the target
df_test_X = scaler.fit_transform(df_test_X)
df_test_X

In [70]:
y_pred = rand_forest.predict(df_test_X)
y_pred

array([0. , 0. , 0. , ..., 0. , 0. , 2.4])

In [71]:
# Add the predicted values as a new column to X_test
df_test['MEAT'] = y_pred

# Now X_test contains the predicted values in the 'y_pred' column
df_test

,MAGIC_KEY,PURCHASE_COUNT,TOTAL_AMOUNT_SPENT,DAY_SINCE_LAST_PURCHASE,AVERAGE_DIFF,10_2018_FIRST_15,11_2018_FIRST_15,12_2018_FIRST_15,1_2019_FIRST_15,2_2019_FIRST_15,...,MEAT_12_2018_FIRST_15,MILK_1_2019_FIRST_15,MEAT_1_2019_FIRST_15,T_PURCHASE_10_2018_FIRST_15,T_PURCHASE_11_2018_FIRST_15,T_PURCHASE_12_2018_FIRST_15,T_PURCHASE_1_2019_FIRST_15,T_PURCHASE_2_2019_FIRST_15,MAGIC_KEY_ENCODED,MEAT
0,2BCFE9C06A7,5,240.00,1,1,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,387282,0.0
1,2C2A872B5A2,2,43.96,87,64,1.0,0.0,1.0,0.0,0.0,...,2.2,0.0,0.0,1.0,0.0,1.0,0.0,0.0,683858,0.0
2,2C6A897671B,3,71.94,1,35,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,830258,0.0
3,2C6F1287F53,10,431.94,1,13,0.0,0.0,1.0,0.0,1.0,...,2.2,0.0,0.0,0.0,0.0,1.0,0.0,1.0,841123,2.2
4,2C658198CC9,3,71.94,25,26,0.0,0.0,1.0,1.0,1.0,...,2.2,10.0,2.2,0.0,0.0,1.0,1.0,1.0,818324,2.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5374,2C0804EFE49,1,11.96,76,0,0.0,0.0,1.0,0.0,0.0,...,2.5,0.0,0.0,0.0,0.0,1.0,0.0,0.0,583509,0.0
5375,2C080B48630,1,12.18,96,0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,583586,0.0
5376,2C08243C58E,1,11.96,29,0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,583875,0.0
5377,2C082C78575,1,12.98,127,0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,583977,0.0
5378,2C083B1F3E5,2,27.92,19,110,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,584154,2.4

In [72]:
solutions = df_test[['MAGIC_KEY', 'MEAT']].copy()
solutions

        MAGIC_KEY  MEAT
0     2BCFE9C06A7   0.0
1     2C2A872B5A2   0.0
2     2C6A897671B   0.0
3     2C6F1287F53   2.2
4     2C658198CC9   2.2
...           ...   ...
5374  2C0804EFE49   0.0
5375  2C080B48630   0.0
5376  2C08243C58E   0.0
5377  2C082C78575   0.0
5378  2C083B1F3E5   2.4

[5379 rows x 2 columns]

In [73]:
solutions.describe()

              MEAT
count  5379.000000
mean      0.755037
std       1.250119
min       0.000000
25%       0.000000
50%       0.000000
75%       1.800000
max      14.136000

In [74]:
solutions.to_csv("Submission.csv", index=False)  # Save test data